<a href="https://colab.research.google.com/github/fiftybucks101/Data-Science_2024/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [ ]:
a

array([0, 1, 2, 3, 4, 5])

In [ ]:
b = np.arange(20).reshape(4,5)
print(b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [ ]:
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [ ]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [ ]:
a = np.array([3,4,5,6])
b = np.arange(4)
c = a - b
c

array([3, 3, 3, 3])

In [ ]:
c = c**2
c

array([9, 9, 9, 9])

In [ ]:
c > 9

array([False, False, False, False])

In [ ]:
c >= 8


array([ True,  True,  True,  True])

In [ ]:
a = np.array([[2,4],
             [1,5]])
b = np.array([[1,3],
             [2,4]])
a * b

array([[ 2, 12],
       [ 2, 20]])

In [ ]:
a @ b

array([[10, 22],
       [11, 23]])

In [ ]:
a.dot(b)

array([[10, 22],
       [11, 23]])

In [ ]:
a = np.random.randn(4,4)
a

array([[ 0.36221483,  0.41893726,  0.59718559, -0.22451968],
       [ 0.35089107,  0.64565424,  0.96928909,  0.68969883],
       [ 3.16166906, -0.02317264, -1.97991829, -1.01674118],
       [ 1.59076988,  1.13424955, -0.04619186,  0.10447837]])

In [ ]:
a = np.random.rand(4,4)
a


array([[0.3840848 , 0.59647506, 0.79900047, 0.80779406],
       [0.53168617, 0.56134288, 0.84807189, 0.01009105],
       [0.22530644, 0.95762242, 0.03475164, 0.41563504],
       [0.23108865, 0.07899079, 0.13781907, 0.51556815]])

In [ ]:
a = np.random.randint(1,100,size=(3,3))
a

array([[68,  7, 51],
       [72,  2,  3],
       [52, 19, 22]])

In [ ]:
b = np.arange(9).reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
b += a
b

array([[68,  8, 53],
       [75,  6,  8],
       [58, 26, 30]])

In [ ]:
from numpy import pi
a = np.ones(4,dtype=np.int32)
b = np.linspace(0,pi,4)
a
b


array([0.        , 1.04719755, 2.0943951 , 3.14159265])

In [ ]:
a

array([1, 1, 1, 1], dtype=int32)

In [ ]:
print(a)

[1 1 1 1]


In [ ]:
a.dtype.name


'int32'

In [ ]:
c = a + b

In [ ]:
c

array([1.        , 2.04719755, 3.0943951 , 4.14159265])

In [ ]:
c.dtype.name

'float64'

In [ ]:
a = np.random.randn(4,5)
a

array([[-1.16663269, -0.72865869, -0.41986952, -0.90644865, -0.14660973],
       [-0.07400471, -0.5526704 ,  1.16371061,  0.66396298,  1.46058656],
       [-0.94828556, -1.95319453, -0.08366759, -0.46861482,  0.19819359],
       [ 0.23209989, -0.09363551, -0.22410944,  0.33259155, -1.08447596]])

In [ ]:
a = np.random.rand(2,3)

In [ ]:
a

array([[0.849457  , 0.62783034, 0.99770289],
       [0.95039556, 0.56878935, 0.43050273]])

In [ ]:
a = np.random.randint(1,50,size=(3,3))
a

array([[ 7, 12,  6],
       [31, 32, 32],
       [ 4, 29, 27]])

In [ ]:
a.sum()

180

In [ ]:
a.mean()

20.0

In [ ]:
a.min()

4

In [ ]:
a.max()

32

In [ ]:
a = np.random.randint(1,20,size=(3,4))
a

array([[10,  9, 18,  2],
       [14, 13,  4, 10],
       [16, 12,  4, 16]])

In [ ]:
a.sum(axis=1)

array([39, 41, 48])

In [ ]:
a.sum(axis=0)

array([40, 34, 26, 28])

In [ ]:
a.cumsum(axis=0)

array([[10,  9, 18,  2],
       [24, 22, 22, 12],
       [40, 34, 26, 28]])

In [ ]:
a.min(axis=0)

array([10,  9,  4,  2])

In [ ]:
a.mean(axis=1)

array([ 9.75, 10.25, 12.  ])

In [ ]:
a = np.arange(5)
np.sqrt(a)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [ ]:
b = np.array([3,4,5,65,5])
np.add(a,b)

array([ 3,  5,  7, 68,  9])

In [ ]:
a = np.arange(10)**2
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
a[5]

25

In [ ]:
a[5:9]

array([25, 36, 49, 64])

In [ ]:
a[:6:2] = 20
a

array([20,  1, 20,  9, 20, 25, 36, 49, 64, 81])

In [ ]:
a[::-1]

array([81, 64, 49, 36, 25, 20,  9, 20,  1, 20])

In [ ]:
a[::-3]

array([81, 36,  9, 20])

In [ ]:
a

array([20,  1, 20,  9, 20, 25, 20, 49, 20, 81])

In [ ]:
a[::3]

array([20,  9, 20, 81])

In [ ]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [ ]:
a[-3::-2]

array([343, 125,  27,   1])

In [ ]:
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [ ]:
b = []
for i in a:
  b = np.append(b,i)

b = b.astype(np.int64)
print(b)

[  0   1   8  27  64 125 216 343 512 729]


In [ ]:
np.empty(5)

array([ 0.,  1.,  8., 27., 64.])

In [ ]:
np.arange(5,15,2)

array([ 5,  7,  9, 11, 13])

In [ ]:
np.linspace(5,15,15)

array([ 5.        ,  5.71428571,  6.42857143,  7.14285714,  7.85714286,
        8.57142857,  9.28571429, 10.        , 10.71428571, 11.42857143,
       12.14285714, 12.85714286, 13.57142857, 14.28571429, 15.        ])

In [ ]:
np.ones((5,5),dtype=np.int64)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
a = np.random.randint(1,100, size=(4,4))
a

array([[65, 55, 24, 35],
       [30, 96, 35, 91],
       [29, 99, 66, 12],
       [89, 71, 79, 84]])

In [ ]:
np.sort(a,axis=0)

array([[29, 55, 24, 12],
       [30, 71, 35, 35],
       [65, 96, 66, 84],
       [89, 99, 79, 91]])

In [ ]:
a = np.random.randint(1,50, size=(3,3))
a

array([[29, 36, 35],
       [38,  9,  2],
       [ 5,  3, 17]])

In [ ]:
print(a[a>10])

[29 36 35 38 17]


In [ ]:
a[1::2]

array([[38,  9,  2]])

In [ ]:
a

array([[29, 36, 35],
       [38,  9,  2],
       [ 5,  3, 17]])

In [ ]:
a = np.sort(a,axis = 0)

In [ ]:
a

array([[ 5,  3,  2],
       [29,  9, 17],
       [38, 36, 35]])

In [ ]:
a.min()

2

In [ ]:
a.cumsum(axis=0)

array([[ 5,  3,  2],
       [34, 12, 19],
       [72, 48, 54]])